#!/usr/bin/env php
<?php
require "./app/Models/Installer.php";
$installer = new App\Models\Installer;

// Performs some checks to see if the system can be installed
$installer->checkCurrentUser();
$installer->checkAllVersions();
$installer->checkPhpConfig();
$installer->checkApacheConfig();

// Initial installation of dependencies
$installer->composerInstall(true);

// After running composerInstall, we finally have a autoload file. Let's load it!
require "./vendor/autoload.php";
// Now, process the options for installation and store that configuration in the .env file
$installer->getOrCreateEnv();
//$installer->dotenv = new \Dotenv\Dotenv(__DIR__);
$installer->dotenv = Dotenv\Dotenv::createUnsafeMutable(__DIR__);
$installer->dotenv->load();
$installer->processEnvFile();

// Finally, we check the database, supervisor and proxy configuration (all of them need access to .env)
$installer->composerInstall(false);
$installer->testProxy();
$installer->checkSupervisor();
$installer->clearCaches();
$installer->checkMySQLConnection();
$installer->checkMySQLConfig();

// now we perform the actual installation!
$installer->migrate();
$installer->postMigrate();
